BlogWebsite/BlogWebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main_app.urls"))

]

BlogWebsite/main_app/urls.py
from django.urls import path
from . import views

app_name = "main_app"

urlpatterns = [
    path("", views.index_page, name="index_page"),
    path("posts/add/", views.add_post, name="add_post"),
    path("posts/details/<post_id>/", views.post_detail, name="post_detail"),
    path("posts/update/<post_id>/", views.update_post, name="update_post"),
    path("games/delete/<post_id>/", views.delete_post, name="delete_post"),
    path("games/search/", views.search_page, name="search_page"),
    ]

BlogWebsite/main_app/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    is_published = models.BooleanField()
    publish_date = models.DateTimeField()

BlogWebsite/main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse, HttpResponseNotFound,Http404
from .models import Post

# Create your views here.

def add_post(request:HttpRequest):

    if request.method == "POST":

        new_post = Post(title=request.POST["title"], content=request.POST["content"],
                         is_published=request.POST["is_published"], publish_date=request.POST["publish_date"])
        new_post.save()
        return redirect("main_app:index_page")

    return render(request, "main_app/add_post.html")



def index_page(request:HttpRequest):

    posts = Post.objects.all()

    return render(request, "main_app/index.html", {"posts" : posts})


def post_detail(request:HttpRequest, post_id):

    try:
        post = Post.objects.get(id=post_id)
    except Post.DoesNotExist:
        raise Http404("Post does not exist")
    return render(request, 'main_app/post_detail.html', {"post" : post})


def update_post(request:HttpRequest, post_id):

    post = Post.objects.get(id=post_id)
    iso_date = post.publish_date.isoformat().replace("T", " ").split("+")[0]
    print(iso_date)
    """ - Title : char field
    - Content : text field
    - is_published : boolean field
    - publish_date : datetime field """
    #updating the post
    if request.method == "POST":
        post.title = request.POST["title"]
        post.content = request.POST["content"]
        post.is_published = request.POST["is_published"]
        post.publish_date = request.POST["publish_date"]
        post.save()

        return redirect("main_app:post_detail", post_id=post.id)

    return render(request, 'main_app/update_post.html', {"post" : post, "iso_date" : iso_date})



def delete_post(request:HttpRequest, post_id):
    
    post = Post.objects.get(id=post_id)
    post.delete()

    return redirect("main_app:index_page")


def search_page(request:HttpRequest):
    search_phrase = request.GET.get("search", "")
    posts = Post.objects.filter(title__contains=search_phrase, is_published=True)

    return render(request, "main_app/search_page.html", {"posts" : posts})

BlogWebsite/main_app/templates/main_app/add_post.html
{% extends 'main_app/base.html' %}

{% block title %} Add New Post {% endblock%}

{% block content %}
<h1>Add Post</h1>
<div class="container">

    <form action="" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Title</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="fill in title" name="title">
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Content</label>
            <textarea class="form-control" id="exampleFormControlInput1" placeholder="fill in content" name="content"></textarea>
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Is Published </label>
            <select class="form-select" aria-label="Default select example" name="is_published">
                <option value="True">Yes</option>
                <option value="False">No</option>

              </select>
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Publish Date</label>
            <input type="date" name="publish_date" />
        </div>

        <div class="mb-3">
            <input type="submit" value="Post" class="btn btn-primary" />
        </div>


    </form>

</div>
{% endblock%}

BlogWebsite/main_app/templates/main_app/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
  <body>
    <div class="container-fluid">

        <!--header-->
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Blog Website</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main_app:add_post' %}">Add Post</a>
                    </li>

                    <div  class="nav-item" >
        
                        <div class="form-outline">
                            <form action="{% url 'main_app:search_page' %}" method="GET" role="search" >
                          <input type="search" name="search" id="form1" class="form-control" placeholder="Search Post"/>
                        </form>
                        </div>
        
                      </div>
                    </ul>


              </div>
              
              
            </div>


          </nav>

            <div class="container p-4">
            {% block content%}
            {% endblock %}
            </div>

        <!-- footer -->
        <div class="container">
            <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
              <div class="col-md-4 d-flex align-items-center">
                <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                  <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
                </a>
                <span class="mb-3 mb-md-0 text-body-secondary">© 2023 Company, Inc</span>
              </div>
          
              <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
                <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
                <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
              </ul>
            </footer>
          </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    </div>
  </body>
</html>

BlogWebsite/main_app/templates/main_app/index.html
{% extends 'main_app/base.html' %}

{% block title %} Show Posts {% endblock%}

{% block content %}
<h1>Here Are All The Posts</h1>

<h3>Posts</h3>
<div class="row">
    {% for post in posts %}
        <div class="col">
            <div class="card" style="width: 18rem;">
                <!-- <img src="..." class="card-img-top" alt="..."> -->
                <div class="card-body">
                <h5 class="card-title">{{ post.title }}</h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col">is_published: {{post.is_published}}</div>
                        <div class="col">{{post.publish_date}}</div>
                    </div>
                </div>    
                <a href="#" class="btn btn-primary">View More</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>


{% endblock %}

BlogWebsite/main_app/templates/main_app/post_detail.html
{% extends 'main_app/base.html' %}

{% block title %}{{post.title}}{% endblock%}

{% block content %}
<div class="container-fluid">
    <h1>{{post.title}}</h1>
    <p>{{post.content}}</p>
    <a href="{% url 'main_app:update_post' post.id %}" class="btn btn-primary">Update Post</a>
    <a href="{% url 'main_app:delete_post' post.id %}" class="btn btn-danger">Delete Post</a>

</div>
    
{% endblock %}

BlogWebsite/main_app/templates/main_app/search_page.html
{% extends 'main_app/base.html' %}

{% block title %} Show Posts {% endblock%}

{% block content %}
<h1>Here Are All The Posts</h1>
<h3>Search results for <span class="text-success">{{request.GET.search}}</span></h3>


<div class="row">
    {% for post in posts %}
        <div class="col">
            <div class="card" style="width: 18rem;">
                <!-- <img src="..." class="card-img-top" alt="..."> -->
                <div class="card-body">
                <h5 class="card-title">{{ post.title }}</h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col">is_published: {{post.is_published}}</div>
                        <div class="col">{{post.publish_date}}</div>
                    </div>
                </div>    
                <a href="{% url 'main_app:post_detail' post.id %}" class="btn btn-primary">View More</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>


{% endblock %}

BlogWebsite/main_app/templates/main_app/update_post.html
{% extends 'main_app/base.html' %}

{% block title %} Update Post {% endblock%}

{% block content%}
<h1>Update Post: {{post.title}}</h1>
<div class="container">

    <form action="{% url 'main_app:update_post' post.id %}" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Title</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="fill in title" name="title" value="{{post.title}}">
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Content</label>
            <textarea class="form-control" id="exampleFormControlInput1" placeholder="fill in content" name="content">{{post.content}}</textarea>
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Is Published </label>
            <select class="form-select" aria-label="Default select example" name="is_published">
                <option value="True" {% if post.is_published == True %} selected {% endif %}>Yes</option>
                <option value="False" {% if post.is_published == False %} selected {% endif %}>No</option>

              </select>
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Publish Date</label>
            <input type="datetime-local" name="publish_date" value="{{iso_date}}" />
        </div>

        <div class="mb-3">
            <input type="submit" value="Update Post" class="btn btn-primary" />
        </div>


    </form>

</div>
{% endblock %}